/**
 * Firestore Data Models
 *
 * Core domain models for the application.
 * Each interface represents a Firestore document structure.
 */

import type { FirestoreTimestamp } from './firebase';

/**
 * User Model
 *
 * Represents a user in the system.
 * Document ID: user's Firebase Auth UID
 * Collection: users
 */
export interface User {
  /** User's unique identifier (same as Firebase Auth UID) */
  id: string;

  /** User's email address (from Google OAuth) */
  email: string;

  /** User's display name (from Google profile) */
  displayName: string;

  /** URL to user's profile picture (from Google profile) */
  photoURL: string | null;

  /** Google OAuth access token for Calendar API integration */
  googleAccessToken: string | null;

  /** When the access token expires */
  tokenExpiresAt: FirestoreTimestamp | null;

  /** Total number of goals created by this user */
  goalsCount: number;

  /** Number of goals completed by this user */
  goalsCompletedCount: number;

  /** User's current streak in days */
  currentStreak: number;

  /** User's longest streak in days */
  longestStreak: number;

  /** Last date user completed a goal (for streak tracking) */
  lastCompletionDate: FirestoreTimestamp | null;

  /** Whether the user has connected their Google Calendar */
  calendarConnected: boolean;

  /** User's timezone (e.g., "America/New_York") */
  timezone: string;

  /** User's notification preferences */
  notificationPreferences: {
    /** Send email notifications */
    email: boolean;
    /** Send goal reminders */
    reminders: boolean;
    /** Send weekly summary */
    weeklySummary: boolean;
  };

  /** When the user account was created */
  createdAt: FirestoreTimestamp;

  /** When the user data was last updated */
  updatedAt: FirestoreTimestamp;
}

/**
 * Goal Model
 *
 * Represents a user's goal or task.
 * Document ID: auto-generated by Firestore
 * Collection: goals
 */
export interface Goal {
  /** Goal's unique identifier */
  id: string;

  /** User ID who created this goal (references User.id) */
  userId: string;

  /** Goal title/name */
  title: string;

  /** Detailed description of the goal */
  description: string;

  /** Goal category for organization */
  category: GoalCategory;

  /** Current status of the goal */
  status: GoalStatus;

  /** Goal priority level */
  priority: GoalPriority;

  /** When the goal should start */
  startDate: FirestoreTimestamp;

  /** Target completion date */
  dueDate: FirestoreTimestamp;

  /** When the goal was actually completed */
  completedAt: FirestoreTimestamp | null;

  /** Whether this goal is recurring */
  recurring: boolean;

  /** Recurrence pattern if recurring is true */
  recurrencePattern: RecurrencePattern | null;

  /** Google Calendar event ID (if synced) */
  calendarEventId: string | null;

  /** Tags for filtering and search */
  tags: string[];

  /** Whether this goal contributes to global stats */
  isPublic: boolean;

  /** Number of days until due date (computed field for queries) */
  daysUntilDue: number;

  /** Whether the goal is overdue (computed field) */
  isOverdue: boolean;

  /** Notes or progress updates */
  notes: string;

  /** When the goal was created */
  createdAt: FirestoreTimestamp;

  /** When the goal was last updated */
  updatedAt: FirestoreTimestamp;
}

/**
 * Goal Category
 *
 * Predefined categories for organizing goals
 */
export type GoalCategory =
  | 'personal'
  | 'work'
  | 'health'
  | 'learning'
  | 'social'
  | 'finance'
  | 'other';

/**
 * Goal Status
 *
 * Lifecycle states of a goal
 */
export type GoalStatus = 'todo' | 'in_progress' | 'completed' | 'cancelled' | 'archived';

/**
 * Goal Priority
 *
 * Importance level of a goal
 */
export type GoalPriority = 'low' | 'medium' | 'high' | 'urgent';

/**
 * Recurrence Pattern
 *
 * Defines how often a goal repeats
 */
export interface RecurrencePattern {
  /** Type of recurrence */
  type: 'daily' | 'weekly' | 'monthly' | 'yearly';

  /** How many intervals between recurrences (e.g., every 2 weeks) */
  interval: number;

  /** Days of week for weekly recurrence (0 = Sunday, 6 = Saturday) */
  daysOfWeek?: number[];

  /** Day of month for monthly recurrence (1-31) */
  dayOfMonth?: number;

  /** When the recurrence ends */
  endDate?: FirestoreTimestamp | null;

  /** Maximum number of occurrences */
  occurrences?: number | null;
}

/**
 * Global Stats Model
 *
 * Community-wide statistics aggregated from all users.
 * Document ID: "current" (single document)
 * Collection: globalStats
 */
export interface GlobalStats {
  /** Document identifier (always "current") */
  id: string;

  /** Total number of registered users */
  totalUsers: number;

  /** Total goals created across all users */
  totalGoals: number;

  /** Total goals completed across all users */
  totalGoalsCompleted: number;

  /** Total goals currently in progress */
  totalGoalsInProgress: number;

  /** Overall community completion rate (percentage) */
  completionRate: number;

  /** Number of active users in the last 7 days */
  activeUsersLast7Days: number;

  /** Number of active users in the last 30 days */
  activeUsersLast30Days: number;

  /** Goals completed today across all users */
  goalsCompletedToday: number;

  /** Goals completed this week across all users */
  goalsCompletedThisWeek: number;

  /** Goals completed this month across all users */
  goalsCompletedThisMonth: number;

  /** Most popular goal category */
  popularCategory: GoalCategory;

  /** Distribution of goals by category */
  categoryDistribution: {
    personal: number;
    work: number;
    health: number;
    learning: number;
    social: number;
    finance: number;
    other: number;
  };

  /** Distribution of goals by status */
  statusDistribution: {
    todo: number;
    in_progress: number;
    completed: number;
    cancelled: number;
    archived: number;
  };

  /** Average goals per user */
  averageGoalsPerUser: number;

  /** Average completion time in days */
  averageCompletionTimeDays: number;

  /** Highest streak across all users */
  highestStreak: number;

  /** User ID with the highest streak */
  highestStreakUserId: string | null;

  /** When the stats were last updated */
  lastUpdated: FirestoreTimestamp;

  /** When the stats document was created */
  createdAt: FirestoreTimestamp;

  /** When the stats were last calculated */
  updatedAt: FirestoreTimestamp;
}

/**
 * Helper Types for CRUD Operations
 */

/** Type for creating a new User (without Firestore metadata) */
export type CreateUser = Omit<User, 'id' | 'createdAt' | 'updatedAt'>;

/** Type for updating a User (partial fields) */
export type UpdateUser = Partial<Omit<User, 'id' | 'createdAt' | 'updatedAt'>>;

/** Type for creating a new Goal (without Firestore metadata) */
export type CreateGoal = Omit<Goal, 'id' | 'createdAt' | 'updatedAt'>;

/** Type for updating a Goal (partial fields) */
export type UpdateGoal = Partial<Omit<Goal, 'id' | 'createdAt' | 'updatedAt'>>;

/** Type for updating GlobalStats (partial fields) */
export type UpdateGlobalStats = Partial<Omit<GlobalStats, 'id' | 'createdAt' | 'updatedAt'>>;
